
[env]
TERM = "xterm-256color"

[font]
size = 13

[font.bold]
family = "JetBrains Mono"
style = "Bold"

[font.italic]
family = "JetBrains Mono"
style = "Italic"

[font.normal]
family = "JetBrains Mono"
style = "Regular"

[font.offset]
x = 1

[scrolling]
history = 10000

[selection]
save_to_clipboard = true
semantic_escape_chars = ''',│`|:"' ()[]{}<>'''

[terminal.shell]
program = "/usr/bin/zsh"

[window]
decorations = "none"
dynamic_padding = true
dynamic_title = true
opacity = 1
startup_mode = "Windowed"

[window.dimensions]
columns = 0
lines = 0

[window.padding]
x = 10
y = 10

[colors]
draw_bold_text_with_bright_colors = true

[general]
live_config_reload = true
import = ["/home/rajiv/dots/.config/alacritty/tokyo-night.toml"]

[terminal]
