add_newline = true

# format = """
# [┌───────────────────>](bold green)
# [│](bold green)$all
# [└─>](bold green) """


[battery]
full_symbol = "🔋"
charging_symbol = "⚡️"
discharging_symbol = "💀"

[[battery.display]]
threshold = 10
style = "bold red"

[[battery.display]]
threshold = 60
style = "bold yellow"

[[battery.display]]
threshold = 100
style = "bold green"

[character]
success_symbol = "[➜](bold green) "
error_symbol = "[✗](bold red) "

[cmd_duration]
min_time = 500
format = "tooks [$duration]($style)"

[directory]
truncation_length = 6
truncate_to_repo = true
style = "bold cyan"
disabled = false

[git_branch]
symbol = "🌱 "
truncation_length = 20
truncation_symbol = "..."
style = "bold purple"
disabled = false

[git_state]
cherry_pick = "[🍒 PICKING](bold red)"
rebase = "REBASING"
merge = "MERGING"
revert = "REVERTING"
bisect = "BISECTING"
am = "AM"
am_or_rebase = "AM/REBASE"
style = "bold yellow"
disabled = false

[git_status]
conflicted = "🏳"
ahead = "🏎💨"
behind = "😰"
diverged = "😵"
up_to_date = "✓"
untracked = "🤷"
stashed = "📦"
modified = "📝"
staged = '[++\($count\)](green)'
renamed = "👅"
deleted = "🗑"

[hostname]
ssh_only = false
trim_at = "."
disabled = false

[line_break]
disabled = false

[memory_usage]
disabled = false
threshold = 40
symbol = "🐏"
style = "bold dimmed green"

[nodejs]
symbol = "⬢ "
style = "bold green"
disabled = false

[python]
symbol = "🐍 "
pyenv_version_name = false
pyenv_prefix = "pyenv"
style = "bold yellow"
disabled = false

[localip]
ssh_only = false
format = "@[$localipv4](bold red) "
disabled = false

# [time]
# format = "🕙%T"
# style_root = "bold red"
# style_user = "bold yellow"
# show_always = true
# disabled = false

[username]
style_root = "bold red"
style_user = "bold yellow"
show_always = false
disabled = false